<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE thunderbots [
<!ELEMENT thunderbots (params , joysticks)>
<!ELEMENT params (category)*>
<!ELEMENT category (category | boolean | integer | double)*>
<!ELEMENT boolean (#PCDATA)>
<!ELEMENT integer (#PCDATA)>
<!ELEMENT double (#PCDATA)>
<!ELEMENT joysticks (joystick)*>
<!ELEMENT joystick (axes , buttons)>
<!ELEMENT axes (mapping)*>
<!ELEMENT buttons (mapping)*>
<!ELEMENT mapping EMPTY>
<!ATTLIST category name CDATA #REQUIRED>
<!ATTLIST boolean name CDATA #REQUIRED>
<!ATTLIST integer name CDATA #REQUIRED>
<!ATTLIST double name CDATA #REQUIRED>
<!ATTLIST joystick name CDATA #REQUIRED>
<!ATTLIST mapping logical CDATA #REQUIRED>
<!ATTLIST mapping physical CDATA #REQUIRED>
]>
<thunderbots>
  <params>
    <category name="Backend">
      <category name="XBee">
        <double name="Loop Delay">0.100</double>
      </category>
    </category>
    <category name="Nav">
      <category name="Pivot">
        <double name="offset angle">80</double>
        <double name="offset distance">0</double>
        <double name="orientation offset">30</double>
      </category>
      <category name="Pivot2">
        <double name="offset angle (degrees)">30</double>
        <double name="offset distance">0.15</double>
        <double name="orientation offset (degrees)">30</double>
      </category>
      <category name="PivotAram">
        <double name="max acceleration">10</double>
        <double name="pivot radius">1.00</double>
      </category>
      <category name="RRT">
        <double name="Buffer behind ball for chase (meters)">0.250</double>
        <double name="Chase angle range for behind target (degrees)">30.0</double>
        <boolean name="Chase ball uses target location to calculate dest">true</boolean>
        <double name="Pivot: offset angle (degrees)">58</double>
        <double name="Pivot: offset distance">0.13</double>
        <double name="Pivot: orientation offset (degrees)">14</double>
      </category>
      <category name="Util">
        <double name="Buffer avoid ball tiny (meters)">0.050</double>
        <double name="Buffer avoid defense area (meters)">0.000</double>
        <double name="Buffer for equal priority friendly robot (meters)">0.100</double>
        <double name="Buffer for higher priority friendly robot (meters)">0.200</double>
        <double name="Buffer for lower priority friendly robot (meters)">0.050</double>
        <double name="The amount of distance to maintain from enemy robots">0.100</double>
      </category>
    </category>
    <category name="oldAI">
      <boolean name="goalie dive for the ball">true</boolean>
      <double name="goalie should ignore direction of ball">0.050</double>
      <integer name="Grid X size">25</integer>
      <integer name="Grid Y size">25</integer>
      <double name="kickoff: angle to separate players (degrees)">40.0</double>
      <double name="Lone goalie distance to goal post (m)">0.300</double>
      <double name="max goalie dist from goal (robot radius)">3.00</double>
      <double name="shrink robot radius">1.100</double>
      <double name="stop: angle to separate players (degrees)">20.0</double>
      <boolean name="Test strategy catch ball">true</boolean>
      <boolean name="Test strategy Ram ball">true</boolean>
      <boolean name="Test strategy recieve ball">true</boolean>
      <boolean name="Test strategy stay own half">true</boolean>
    </category>
    <category name="RC">
      <category name="Circle">
        <double name="amount to scale controller velocities by">2.00</double>
      </category>
      <category name="fuzzy2">
        <double name="max acc">3.00</double>
      </category>
      <category name="PID3">
        <double name="anglular differential (-ve)">-1.00</double>
        <double name="anglular max velocity">15.00</double>
        <double name="anglular proportional">15.00</double>
        <double name="angular slowdown when translating">1.500</double>
        <boolean name="flip trans&amp;ang slowdown (CARE)">false</boolean>
        <boolean name="reduce angular velocity when translating">false</boolean>
        <double name="x to y ratio">0.810</double>
        <double name="xy differential (-ve)">-1.00</double>
        <double name="xy max acceleration">5.00</double>
        <double name="xy max velocity">12.00</double>
        <double name="xy proportional">12.00</double>
      </category>
    </category>
    <category name="STP">
      <category name="Action">
        <category name="block">
          <double name="block threshold distance in terms of robot radius">3.000</double>
        </category>
        <category name="Goalie">
          <double name="Lone Goalie: distance to goal post (m)">0.300</double>
        </category>
        <category name="shoot">
          <double name="Angle threshold (in degrees) that defines passing accuracy, smaller is more accurate">10.0</double>
          <double name="Decay constant for the ball velocity">0.100</double>
          <double name="kicking speed for making a pass">4.75</double>
          <double name="reduced radius for calculating best shot (robot radius ratio)">0.800</double>
        </category>
        <category name="spin">
          <double name="change in orientation every time tick for move spin">0.500</double>
        </category>
      </category>
      <category name="ball">
        <double name="circle radius in front of robot to consider possesion (meters)">0.100</double>
        <boolean name="Smart possess ball (instead of has ball only)">true</boolean>
      </category>
      <category name="defense">
        <boolean name="goalie hug switch">false</boolean>
        <double name="max goalie dist from goal (robot radius)">3.00</double>
        <double name="shrink robot radius">1.100</double>
      </category>
      <category name="evaluation">
        <double name="speed goalie should ignore direction of ball">0.050</double>
        <double name="Steal threshold: distance of ball from enemy (robot radius)">1.100</double>
      </category>
      <category name="offense">
        <double name="ball distance weight">1.000</double>
        <double name="enemy avoidance distance (robot radius)">4.00</double>
        <integer name="grid x size">25</integer>
        <integer name="grid y size">25</integer>
      </category>
      <category name="pass">
        <double name="ball goal distance weight">1.000</double>
        <double name="enemy avoidance distance (robot radius)">4.00</double>
      </category>
      <category name="play">
        <double name="kickoff: angle to separate players (degrees)">40.0</double>
      </category>
      <category name="predicates">
        <double name="enemy avoidance distance (robot radius)">3.00</double>
      </category>
      <category name="shoot">
        <double name="Angle threshold (in degrees) that defines shoot accuracy, smaller is more accurate">0.0</double>
      </category>
      <category name="STP">
        <boolean name="Goalie is lowest index">true</boolean>
        <integer name="Goalie pattern index">0</integer>
      </category>
      <category name="Tactic">
        <double name="stop: angle to separate players (degrees)">20.0</double>
      </category>
      <category name="test_pass">
        <double name=" angle tolerance that the passer needs to be with respect to the passee">20.0</double>
        <double name=" angle tolerance that the passer needs to be with respect to the target">30.0</double>
        <double name=" distance tolerance that the passee needs to be with respect to the passer shot">0.050</double>
        <integer name="passing target points">0</integer>
        <double name="velocity to ignore">0.100</double>
      </category>
      <category name="test_pass2">
        <double name=" angle tolerance that the passer needs to be with respect to the passee">20.0</double>
        <double name=" angle tolerance that the passer needs to be with respect to the target">30.0</double>
        <double name=" distance tolerance that the passee needs to be with respect to the passer shot">0.050</double>
        <double name="Hack to get reciever to move more quickly to intercept pos by modifying dest (meters)">0.030</double>
        <integer name="passing target points">0</integer>
        <double name="velocity to ignore">0.100</double>
      </category>
      <category name="util">
        <double name="distance for ball possesion (x ball radius)">2.000</double>
        <double name="if dribble &gt; this time, force shoot (sec)">2.00</double>
        <boolean name="posses ball is has ball">true</boolean>
        <double name="Shooting Accuracy General (degrees)">10.0</double>
        <double name="time we can prepare during special plays (sec)">3</double>
      </category>
    </category>
  </params>
  <joysticks>
    <joystick name="Logitech Logitech Dual Action">
      <axes>
        <mapping logical="0" physical="3"/>
        <mapping logical="1" physical="2"/>
        <mapping logical="2" physical="0"/>
        <mapping logical="3" physical="1"/>
      </axes>
      <buttons>
        <mapping logical="dribble" physical="1"/>
        <mapping logical="kick" physical="3"/>
        <mapping logical="scram" physical="2"/>
      </buttons>
    </joystick>
    <joystick name="Xbox 360 Wireless Receiver">
      <axes>
        <mapping logical="0" physical="4"/>
        <mapping logical="1" physical="3"/>
        <mapping logical="2" physical="0"/>
        <mapping logical="3" physical="1"/>
      </axes>
      <buttons>
        <mapping logical="dribble" physical="0"/>
        <mapping logical="kick" physical="3"/>
        <mapping logical="scram" physical="1"/>
      </buttons>
    </joystick>
  </joysticks>
</thunderbots>
